---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-10.04
  run_list:
    - recipe[apt]
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: debian-7.4
  run_list:
    - recipe[apt]
- name: centos-5.10
- name: centos-6.4
- name: fedora-19
# TODO: bash and ports need to be installed by hand
# - name: freebsd-9.2

suites:
- name: default
  run_list:
    - recipe[mysql::server]
    - recipe[mysql_tuning::default]
  attributes:
