---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-5.11
- name: centos-6.7
- name: centos-7.1
- name: debian-6.0.10
  run_list: recipe[apt]
- name: debian-7.9
  run_list: recipe[apt]
# mysql5: undefined method `[]' for nil:NilClass
- name: debian-8.2
  run_list: recipe[apt]
# mysql6: undefined method `[]' for nil:NilClass
- name: fedora-19
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-20_chef-provisionerless.box
# mysql5: undefined method `[]' for nil:NilClass
- name: fedora-21
- name: ubuntu-10.04
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
# mysql5: undefined method `[]' for nil:NilClass
- name: ubuntu-15.04
  run_list: recipe[apt]

suites:
- name: default
  run_list: recipe[mysql_tuning_test]
- name: lwrp
  run_list: recipe[mysql_tuning_test::lwrp]
- name: ohai
  run_list: recipe[mysql_tuning_test::ohai_plugin]
